services:
  - type: web
    name: formatx-backend
    repo: https://github.com/Kevin-cell111/formatx-converter
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "10000"
    healthCheckPath: /api/health
